# Generated by Django 4.0.2 on 2022-07-28 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_barrio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BarrioDet',
            fields=[
                ('id_barrio_det', models.AutoField(primary_key=True, serialize=False)),
                ('mz', models.IntegerField()),
                ('pc', models.IntegerField()),
                ('id_barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.barrio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMinuta',
            fields=[
                ('id_detalle_minuta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Efectivo',
            fields=[
                ('id_efectivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.DecimalField(decimal_places=2, max_digits=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nac', models.DateField()),
                ('detalle_persona', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tipo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('constrasenia', models.CharField(max_length=30)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='MinutaGeneral',
            fields=[
                ('id_minuta_general', models.AutoField(primary_key=True, serialize=False)),
                ('importe_minuta', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('id_detalle_minuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.detalleminuta')),
                ('id_efectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.efectivo')),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.tipopago')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('id_barrio_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.barriodet')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.persona')),
            ],
        ),
    ]
