# Generated by Django 4.0.2 on 2022-07-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nro_cuota_cliente', models.IntegerField()),
                ('tipo_cuota', models.CharField(max_length=40)),
                ('cuota_total_pesos', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('cuota_mas_interes', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('porcentaje_gastos', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('gastos_pesos', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('interes_pesos', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('detalle', models.CharField(max_length=500)),
                ('observaciones', models.CharField(max_length=500)),
                ('tipo_pago', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='barriodet',
            name='id_barrio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_barrio_det',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_persona',
        ),
        migrations.RemoveField(
            model_name='minutageneral',
            name='id_detalle_minuta',
        ),
        migrations.RemoveField(
            model_name='minutageneral',
            name='id_efectivo',
        ),
        migrations.RemoveField(
            model_name='minutageneral',
            name='id_tipo_pago',
        ),
        migrations.RemoveField(
            model_name='minutageneral',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_persona',
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
        migrations.DeleteModel(
            name='BarrioDet',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DetalleMinuta',
        ),
        migrations.DeleteModel(
            name='Efectivo',
        ),
        migrations.DeleteModel(
            name='MinutaGeneral',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='TipoPago',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
