# Generated by Django 3.2.6 on 2022-08-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0003_auto_20220802_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrioDueñoDet',
            fields=[
                ('id_barrio_det', models.AutoField(primary_key=True, serialize=False)),
                ('mz', models.IntegerField()),
                ('pc', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='clientebarriocuotas',
            old_name='id_cliente_barrio_det',
            new_name='id_cliente_barrio_cuotas',
        ),
        migrations.RemoveField(
            model_name='barrio',
            name='id_barrio_det',
        ),
        migrations.RemoveField(
            model_name='barrio',
            name='mz',
        ),
        migrations.RemoveField(
            model_name='barrio',
            name='pc',
        ),
        migrations.AddField(
            model_name='barrio',
            name='detalle_barrio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='barrio',
            name='nombre_barrio',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='detalle_cliente',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientebarriocuotas',
            name='detalle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clientebarriocuotas',
            name='observaciones',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='constrasenia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.TextField(max_length=20),
        ),
        migrations.DeleteModel(
            name='BarrioDet',
        ),
        migrations.AddField(
            model_name='barriodueñodet',
            name='id_barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.barrio'),
        ),
        migrations.AddField(
            model_name='barriodueñodet',
            name='id_dueño_barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.dueñobarrio'),
        ),
    ]
