# Generated by Django 3.2.6 on 2022-08-03 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0004_auto_20220803_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpoCuota',
            fields=[
                ('id_tpo_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TpoPago',
            fields=[
                ('id_tpo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientebarriocuotas',
            name='tipo_cuota',
        ),
        migrations.RemoveField(
            model_name='clientebarriocuotas',
            name='tipo_pago',
        ),
        migrations.AddField(
            model_name='clientebarriocuotas',
            name='id_tpo_cuota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minutas.tpocuota'),
        ),
        migrations.AddField(
            model_name='clientebarriocuotas',
            name='id_tpo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minutas.tpopago'),
        ),
    ]
