from django import forms
from .models import *

class CajaForm(forms.ModelForm):
    class Meta:

        model = General

        fields = (
            'dv1_m',
            'dv1_ga',
            'dv1_tar',
            'dv1_ga_tar',
            'dv2_m',
            'dv2_ga',
            'dv2_tar',
            'dv2_ga_tar',
            'rigo_m',
            'rigo_ga',
            'rigo_tar',
            'rigo_ga_tar',
            'si_m',
            'si_ga',
            'si_tar',
            'si_ga_tar',
            'si2_m',
            'si2_ga',
            'si2_tar',
            'si2_ga_tar',
            'der_m',
            'der_ga',
            'der_tar',
            'der_ga_tar',
            'dea_m',
            'dea_ga',
            'dea_tar',
            'dea_ga_tar',
            'dee_m',
            'dee_ga',
            'dee_tar',
            'dee_ga_tar',
            'sa_m',
            'sa_ga',
            'sa_tar',
            'sa_ga_tar',
            'ceto_m',
            'ceto_ga',
            'ceto_tar',
            'ceto_ga_tar',
            'gara_m',
            'gara_ga',
            'gara_tar',
            'gara_ga_tar',
            'apodaca_m',
            'apodaca_ga',
            'apodaca_tar',
            'apodaca_ga_tar'
        )

        widgets = {
            'dv1_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'dv1_m', 'onKeyUp': 'total_M()'}),
            'dv1_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'dv1_ga', 'onKeyUp': 'total_GA()'}),
            'dv1_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'dv1_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'dv2_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'dv2_m', 'onKeyUp': 'total_M()'}),
            'dv2_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'dv2_m', 'onKeyUp': 'total_GA()'}),
            'dv2_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'dv2_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'rigo_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'rigo_m', 'onKeyUp': 'total_M()'}),
            'rigo_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'rigo_m', 'onKeyUp': 'total_GA()'}),
            'rigo_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'rigo_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'si_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'si_m', 'onKeyUp': 'total_M()'}),
            'si_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'si_m', 'onKeyUp': 'total_GA()'}),
            'si_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'si_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'si2_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'si2_m', 'onKeyUp': 'total_M()'}),
            'si2_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'si2_m', 'onKeyUp': 'total_GA()'}),
            'si2_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'si2_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'der_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'der_m', 'onKeyUp': 'total_M()'}),
            'der_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'der_m', 'onKeyUp': 'total_GA()'}),
            'der_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'der_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'dea_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'dea_m', 'onKeyUp': 'total_M()'}),
            'dea_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'dea_m', 'onKeyUp': 'total_GA()'}),
            'dea_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'dea_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'dee_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'dee_m', 'onKeyUp': 'total_M()'}),
            'dee_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'dee_m', 'onKeyUp': 'total_GA()'}),
            'dee_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'dee_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'sa_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'sa_m', 'onKeyUp': 'total_M()'}),
            'sa_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'sa_m', 'onKeyUp': 'total_GA()'}),
            'sa_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'sa_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'ceto_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'ceto_m', 'onKeyUp': 'total_M()'}),
            'ceto_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'ceto_m', 'onKeyUp': 'total_GA()'}),
            'ceto_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'ceto_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'gara_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'gara_m', 'onKeyUp': 'total_M()'}),
            'gara_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'gara_m', 'onKeyUp': 'total_GA()'}),
            'gara_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'gara_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'apodaca_m': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'apodaca_m', 'onKeyUp': 'total_M()'}),
            'apodaca_ga': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta', 'id': 'apodaca_m', 'onKeyUp': 'total_GA()'}),
            'apodaca_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
            'apodaca_ga_tar': forms.NumberInput(attrs={'class': 'form-control form-caja-minuta'}),
        }
        
        labels = {

        }