from django.db import models

# Create your models here.
class General(models.Model):
    id_general = models.AutoField(primary_key=True)
    fecha = models.DateField(auto_now_add=True, blank=True)
    hora_ing_efectivo = models.DateTimeField(auto_now=True, blank=True)
    hora_ing_minuta = models.DateTimeField(auto_now=True, blank=True)
    efectivo_total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    efectivo_mpc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    efectivo_banco = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    total_minuta = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    total_gasto_adm = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    total_rendir = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    calculo_total_minuta = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dv1_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dv1_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dv1_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dv1_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dv2_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dv2_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dv2_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dv2_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    rigo_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    rigo_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    rigo_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    rigo_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    si_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    si_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    si_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    si_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    si2_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    si2_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    si2_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    si2_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    der_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    der_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    der_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    der_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dea_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dea_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dea_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dea_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dee_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dee_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dee_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dee_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    sa_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    sa_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    sa_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    sa_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    ceto_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    ceto_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    ceto_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    ceto_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    debitos_clientes = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    debitos_inversiones = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    debitos_pagos_a = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dolares_en_pesos = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    cheques = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    adhesiones = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    adhesiones_aei = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    cuotas_aei = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    adhesiones_esperanza = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    cuotas_esperanza = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    derecho_posesion = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    agrimensor = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    cuotas_inm_particulares = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    ingr_gastos_admin = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    vehiculos_financiados = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    bm_suscripciones = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    bm_cuotas = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    intereses_moratorios = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    adelantos_personal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    egresos = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    cotizacion_dolar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    efectivo_mpc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    efectivo_bm = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    efectivo_aei = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    efectivo_esperanza = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dolares = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    num_minuta = models.IntegerField()
    personal = models.CharField(max_length=50, blank=True)
    sobrante = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)

