from pyexpat import model
from django.db import models

# Create your models here.

class General(models.Model):
    id_general = models.AutoField(primary_key=True)
    dv1_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    dv1_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    dv1_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dv1_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dv2_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dv2_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dv2_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dv2_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    rigo_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    rigo_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    rigo_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    rigo_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si2_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si2_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si2_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si2_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    der_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    der_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    der_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    der_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dea_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dea_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dea_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dea_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dee_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dee_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dee_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dee_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    sa_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    sa_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    sa_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    sa_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ceto_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ceto_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ceto_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ceto_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    gara_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    gara_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    gara_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    gara_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    apodaca_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    apodaca_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    apodaca_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    apodaca_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    total_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    total_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    total_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    total_m_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    total_ingresado = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )


"""
class General(models.Model):
    id_general = models.AutoField(primary_key=True)
    fecha = models.DateField(auto_now_add=True, blank=True)
    hora_ing_efectivo = models.DateTimeField(auto_now=True, blank=True)
    hora_ing_minuta = models.DateTimeField(auto_now=True, blank=True)
    efectivo_total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    efectivo_mpc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    efectivo_banco = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    total_minuta = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    total_gasto_adm = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    total_rendir = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    calculo_total_minuta = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ### campos minuta
    dv1_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    dv1_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    dv1_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dv1_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dv2_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dv2_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dv2_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dv2_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    rigo_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    rigo_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    rigo_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    rigo_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si2_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si2_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si2_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    si2_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    der_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    der_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    der_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    der_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dea_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dea_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dea_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dea_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dee_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dee_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dee_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dee_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    sa_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    sa_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    sa_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    sa_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ceto_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ceto_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ceto_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ceto_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    gara_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    gara_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    gara_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    gara_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    apodaca_m = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    apodaca_ga = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    apodaca_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    apodaca_ga_tar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    # fin campos detalles
    cotizacion_dolar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ingreso_mpc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ingreso_bm = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ingreso_aei = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ingreso_esperanza = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dolares = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    num_minuta = models.IntegerField()
    personal = models.CharField(max_length=50, blank=True)
    sobrante = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )

class EspMinuta(models.Model):
    id_esp_minuta = models.AutoField(primary_key=True)
    debitos_clientes = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    debitos_inversiones = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    debitos_pagos_a = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    dolares_en_pesos = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    cheques = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    adhesiones = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    adhesiones_aei = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    cuotas_aei = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    adhesiones_esperanza = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    cuotas_esperanza = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    derecho_posesion = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    agrimensor = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    cuotas_inm_particulares = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    ingr_gastos_admin = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    vehiculos_financiados = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    bm_suscripciones = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    bm_cuotas = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    intereses_moratorios = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    adelantos_personal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )
    egresos = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, )

class DetMinuta(models.Model):
    id_general = models.ForeignKey(General, on_delete=models.CASCADE)
    id_esp_minuta = models.ForeignKey(EspMinuta, on_delete=models.CASCADE)

"""