# Generated by Django 4.1 on 2022-11-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id_general', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('cotizacion_dolar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv1_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv1_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv1_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv1_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv2_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv2_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv2_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dv2_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rigo_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rigo_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rigo_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rigo_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('si_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('si_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('si_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('si_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('si2_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('si2_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('si2_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('si2_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('der_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('der_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('der_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('der_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dea_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dea_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dea_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dea_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dee_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dee_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dee_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dee_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sa_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sa_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sa_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sa_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ceto_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ceto_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ceto_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ceto_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gara_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gara_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gara_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gara_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apodaca_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apodaca_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apodaca_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apodaca_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_m_ga_tar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ingresado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinDet',
            fields=[
                ('id_mindet', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('detalle', models.CharField(blank=True, max_length=50)),
                ('especificacion', models.CharField(blank=True, max_length=50)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.general')),
            ],
        ),
    ]
