# Generated by Django 4.1 on 2022-11-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
