# Generated by Django 3.2.6 on 2022-08-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_auto_20220825_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='Sobrante',
            new_name='sobrante',
        ),
    ]
