# Generated by Django 4.1 on 2022-09-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_alter_general_adelantos_personal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspMinuta',
            fields=[
                ('id_esp_minuta', models.AutoField(primary_key=True, serialize=False)),
                ('debitos_clientes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debitos_inversiones', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debitos_pagos_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dolares_en_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cheques', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adhesiones', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adhesiones_aei', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuotas_aei', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adhesiones_esperanza', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuotas_esperanza', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('derecho_posesion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agrimensor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuotas_inm_particulares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingr_gastos_admin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehiculos_financiados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bm_suscripciones', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bm_cuotas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('intereses_moratorios', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adelantos_personal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('egresos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='general',
            old_name='adelantos_personal',
            new_name='ingreso_aei',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='adhesiones',
            new_name='ingreso_bm',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='adhesiones_aei',
            new_name='ingreso_esperanza',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='adhesiones_esperanza',
            new_name='ingreso_mpc',
        ),
        migrations.RemoveField(
            model_name='general',
            name='agrimensor',
        ),
        migrations.RemoveField(
            model_name='general',
            name='bm_cuotas',
        ),
        migrations.RemoveField(
            model_name='general',
            name='bm_suscripciones',
        ),
        migrations.RemoveField(
            model_name='general',
            name='cheques',
        ),
        migrations.RemoveField(
            model_name='general',
            name='cuotas_aei',
        ),
        migrations.RemoveField(
            model_name='general',
            name='cuotas_esperanza',
        ),
        migrations.RemoveField(
            model_name='general',
            name='cuotas_inm_particulares',
        ),
        migrations.RemoveField(
            model_name='general',
            name='debitos_clientes',
        ),
        migrations.RemoveField(
            model_name='general',
            name='debitos_inversiones',
        ),
        migrations.RemoveField(
            model_name='general',
            name='debitos_pagos_a',
        ),
        migrations.RemoveField(
            model_name='general',
            name='derecho_posesion',
        ),
        migrations.RemoveField(
            model_name='general',
            name='dolares_en_pesos',
        ),
        migrations.RemoveField(
            model_name='general',
            name='efectivo_aei',
        ),
        migrations.RemoveField(
            model_name='general',
            name='efectivo_bm',
        ),
        migrations.RemoveField(
            model_name='general',
            name='efectivo_esperanza',
        ),
        migrations.RemoveField(
            model_name='general',
            name='egresos',
        ),
        migrations.RemoveField(
            model_name='general',
            name='ingr_gastos_admin',
        ),
        migrations.RemoveField(
            model_name='general',
            name='intereses_moratorios',
        ),
        migrations.RemoveField(
            model_name='general',
            name='vehiculos_financiados',
        ),
        migrations.CreateModel(
            name='DetMinuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_esp_minuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.espminuta')),
                ('id_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.general')),
            ],
        ),
    ]
