# Generated by Django 4.1 on 2022-09-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_espminuta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='calculo_total_minuta',
            new_name='total_ga',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='cotizacion_dolar',
            new_name='total_ingresado',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='dolares',
            new_name='total_m',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='efectivo_banco',
            new_name='total_m_ga_tar',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='efectivo_mpc',
            new_name='total_tar',
        ),
        migrations.RemoveField(
            model_name='general',
            name='efectivo_total',
        ),
        migrations.RemoveField(
            model_name='general',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='general',
            name='hora_ing_efectivo',
        ),
        migrations.RemoveField(
            model_name='general',
            name='hora_ing_minuta',
        ),
        migrations.RemoveField(
            model_name='general',
            name='ingreso_aei',
        ),
        migrations.RemoveField(
            model_name='general',
            name='ingreso_bm',
        ),
        migrations.RemoveField(
            model_name='general',
            name='ingreso_esperanza',
        ),
        migrations.RemoveField(
            model_name='general',
            name='ingreso_mpc',
        ),
        migrations.RemoveField(
            model_name='general',
            name='num_minuta',
        ),
        migrations.RemoveField(
            model_name='general',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='general',
            name='sobrante',
        ),
        migrations.RemoveField(
            model_name='general',
            name='total_gasto_adm',
        ),
        migrations.RemoveField(
            model_name='general',
            name='total_minuta',
        ),
        migrations.RemoveField(
            model_name='general',
            name='total_rendir',
        ),
        migrations.DeleteModel(
            name='DetMinuta',
        ),
        migrations.DeleteModel(
            name='EspMinuta',
        ),
    ]
