# Generated by Django 4.1 on 2022-08-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dueniosBarrios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrios',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_barrio', models.CharField(max_length=50)),
                ('id_dueniobarrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dueniosBarrios.dueniosbarrios')),
            ],
        ),
    ]
